export type AgentDataProp = {
  name: string;
  pais: string;
  classe: string;
  habilidades: string[];
  orbes: number;
  id: number;
  image: string;
};

const agentData = [
  {
    name: 'Astra',
    pais: 'Gana',
    classe: 'Controlador',
    habilidades: ['Q - pulso nova',
      'E - nebulosa', 'C - poço gravitacional', 'X - divisa cósmica'],
    orbes: 7,
    id: 1,
    image: '/src/images/astra.png',
  },
  {
    name: 'Breach',
    pais: 'Suécia',
    classe: 'Iniciador',
    habilidades: ['Q - estopim',
      'E - falha tectônica', 'C - pós-choque', 'X - onda trovejante'],
    orbes: 7,
    id: 2,
    image: '/src/images/breach.png',
  },
  {
    name: 'Brimstone',
    pais: 'Estados Unidos',
    classe: 'Controlador',
    habilidades: ['Q - incendiário',
      'E - fumaça celeste', 'C - sinalizador estimulante', 'X - ataque orbital'],
    orbes: 7,
    id: 3,
    image: '/src/images/brimstone.png',
  },
  {
    name: 'Chamber',
    pais: 'França',
    classe: 'Sentinela',
    habilidades: ['Q - caçador de cabeças',
      'E - rendezvous', 'C - marca registrada', 'X - tour de force'],
    orbes: 7,
    id: 4,
    image: '/src/images/chamber.png',
  },
  {
    name: 'Cypher',
    pais: 'Marrocos',
    classe: 'Sentinela',
    habilidades: ['Q - jaula cibernética',
      'E - câmera de vigilância', 'C - fio-armadilha', 'X - assalto neural'],
    orbes: 6,
    id: 5,
    image: '/src/images/cypher.png',
  },
  {
    name: 'Fade',
    pais: 'Turquia',
    classe: 'Iniciadora',
    habilidades: ['Q - clausura', 'E - assombrar', 'C - espreitador', 'X - véu da noite'],
    orbes: 7,
    id: 6,
    image: '/src/images/fade.png',
  },
  {
    name: 'Jett',
    pais: 'Coreia do Sul',
    classe: 'Duelista',
    habilidades: ['Q - corrente ascendente',
      'E - brisa de impulso', 'C - erupção das brumas', 'X - tormenta de aço'],
    orbes: 7,
    id: 7,
    image: '/src/images/jett.png',
  },
  {
    name: 'Kay/o',
    pais: 'Undefined',
    classe: 'Iniciador',
    habilidades: ['Q - granada/clarão',
      'E - ponto/zero', 'C - frag/mento', 'X - anular/CMD'],
    orbes: 7,
    id: 8,
    image: '/src/images/kayo.png',
  },
  {
    name: 'Killjoy',
    pais: 'Alemanha',
    classe: 'Sentinela',
    habilidades: ['Q - robô de alarme',
      'E - torreta', 'C - nanoenxame', 'X - confinamento'],
    orbes: 7,
    id: 9,
    image: '/src/images/killjoy.png',
  },
  {
    name: 'Neon',
    pais: 'Filipinas',
    classe: 'Duelista',
    habilidades: ['Q - ricochete elétrico',
      'E - equipamento voltaico', 'C - via expressa', 'X - sobrecarga'],
    orbes: 7,
    id: 10,
    image: '/src/images/neon.png',
  },
  {
    name: 'Omen',
    pais: 'Undefined',
    classe: 'Controlador',
    habilidades: ['Q - paranoia',
      'E - manto sombrio', 'C - passos tenebrosos', 'X - salto das sombras'],
    orbes: 7,
    id: 11,
    image: '/src/images/omen.png',
  },
  {
    name: 'Phoenix',
    pais: 'Reino Unido',
    classe: 'Duelista',
    habilidades: ['Q - bola curva',
      'E - mãos quentes', 'C - labareda', 'X - renascimento'],
    orbes: 6,
    id: 12,
    image: '/src/images/phoenix.png',
  },
  {
    name: 'Raze',
    pais: 'Brasil',
    classe: 'Duelista',
    habilidades: ['Q - cargas de explosivos',
      'E - cartucho de tinta', 'C - bumba', 'X - estraga-prazeres'],
    orbes: 7,
    id: 13,
    image: '/src/images/raze.png',
  },
  {
    name: 'Reyna',
    pais: 'México',
    classe: 'Duelista',
    habilidades: ['Q - devorar', 'E - dispensar', 'C - olhar voraz', 'X - imperatriz'],
    orbes: 6,
    id: 14,
    image: '/src/images/reyna.png',
  },
  {
    name: 'Sage',
    pais: 'China',
    classe: 'Sentinela',
    habilidades: ['Q - orbe de lentidão',
      'E - orbe curativo', 'C - orbe de barreira', 'X - ressurreição'],
    orbes: 8,
    id: 15,
    image: '/src/images/sage.png',
  },
  {
    name: 'Skye',
    pais: 'Austrália',
    classe: 'Iniciador',
    habilidades: ['Q - predador explosivo',
      'E - luz desbravadora', 'C - reflorescer', 'X - rastreadores'],
    orbes: 6,
    id: 16,
    image: '/src/images/skye.png',
  },
  {
    name: 'Sova',
    pais: 'Rússia',
    classe: 'Iniciador',
    habilidades: ['Q - flecha de choque',
      'E - flecha rastreadora', 'C - drone coruja', 'X - fúria do caçador'],
    orbes: 8,
    id: 17,
    image: '/src/images/sova.png',
  },
  {
    name: 'Viper',
    pais: 'Estados Unidos',
    classe: 'Controlador',
    habilidades: ['Q - nuvem venenosa',
      'E - cortina tóxica', 'C - veneno de cobra', 'X - poço peçonhento'],
    orbes: 7,
    id: 18,
    image: '/src/images/viper.png',
  },
  {
    name: 'Yoru',
    pais: 'Japão',
    classe: 'Duelista',
    habilidades: ['Q - ponto cego',
      'E - passagem dimensional', 'C - distração', 'X - espionagem dimensional'],
    orbes: 6,
    id: 19,
    image: '/src/images/yoru.png',
  },

];

export default agentData;
